name: Daily VNN Events

on:
  schedule:
    - cron: "15 9 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r vnn-events/requirements.txt

      - name: Generate feeds
        env:
          PUBLIC_BASE_URL: https://jackbrandt1995.github.io/vnn-events
          OUTPUT_DIR: docs
        run: |
          python vnn-events/run.py

      - name: Commit updated feeds
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/events.json docs/events.ics || true
          git diff --cached --quiet || git commit -m "chore: update event feeds"
          git push
